[tool.poetry]
name = "finradar"
version = "0.1.0"
description = ""
authors = ["wangf <ten2net@163.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
autogen = "^1.0.16"
chainlit = "^1.0.16"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
